// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2aNeEf-Si36lIozRUnJDUNNmfoIFXVbo',
    appId: '1:329737191860:web:f229ac51f76f246e20b2e1',
    messagingSenderId: '329737191860',
    projectId: 'insta-crawller-flutter',
    authDomain: 'insta-crawller-flutter.firebaseapp.com',
    storageBucket: 'insta-crawller-flutter.appspot.com',
    measurementId: 'G-ZVGE1MFR84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnu7DHzBkCmcUVXpjYc8EffqhMceS4mW8',
    appId: '1:329737191860:android:ff525a87b53e63a320b2e1',
    messagingSenderId: '329737191860',
    projectId: 'insta-crawller-flutter',
    storageBucket: 'insta-crawller-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDRuqIcQZNmDgT6Z_lLZFvO62LJfVze0',
    appId: '1:329737191860:ios:8cce3a9e01c4c1be20b2e1',
    messagingSenderId: '329737191860',
    projectId: 'insta-crawller-flutter',
    storageBucket: 'insta-crawller-flutter.appspot.com',
    iosClientId: '329737191860-1gmj1gr0h29cjdb1c4prreoho292vncf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
